In [ ]:
!pip install -q transformers datasets accelerate peft bitsandbytes trl

## Importing Nesscary Libraries

In [ ]:
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)

from peft import LoraConfig, get_peft_model
import torch

## Loading Data

In [3]:
ds = load_dataset("LLukas22/fiqa", split="train")

print(ds[0])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

train.json:   0%|          | 0.00/16.4M [00:00<?, ?B/s]

test.json: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/14511 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2561 [00:00<?, ? examples/s]

{'question': 'What do brokers do with bad stock?', 'answer': "For every seller, there's a buyer. Buyers may have any reason for wanting to buy (bargain shopping, foolish belief in a crazy business, etc).  The party (brokerage, market maker, individual) owning the stock at the time the company goes out of business is the loser . But in a general panic, not every company is going to go out of business. So the party owning those stocks can expect to recover some, or all, of the value at some point in the future. Brokerages all reserve the right to limit margin trading (required for short selling), and during a panic would likely not allow you to short a stock they feel is a high risk for them."}

## Defining Prompt template

In [4]:
def format_example(example):
    text = f"""### Question:
{example['question']}

### Answer:
{example['answer']}
"""
    return {"text": text}

formatted_ds = ds.map(format_example)

Map:   0%|          | 0/14511 [00:00<?, ? examples/s]

## Model Loading and Inintiating Tokeniser

In [5]:
model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16
)

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/2.20G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [6]:
def tokenize(example):
    return tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

tokenized_ds = formatted_ds.map(tokenize, batched=True)

Map:   0%|          | 0/14511 [00:00<?, ? examples/s]

## Configrating LoRa

In [8]:
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

Requirement already satisfied: torchao in /usr/local/lib/python3.12/dist-packages (0.10.0)
Collecting torchao
  Downloading torchao-0.17.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (20 kB)
Downloading torchao-0.17.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 59.6 MB/s eta 0:00:00
Installing collected packages: torchao
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
Successfully installed torchao-0.17.0

WARNING:torchao:Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.10.0+cu128).

trainable params: 1,126,400 || all params: 1,101,174,784 || trainable%: 0.1023

* **trainable params: 1,126,400**
*  **all params: 1,101,174,784**
* **trainable%: 0.1023**

## Training Arguments

In [9]:
training_args = TrainingArguments(
    output_dir="./finance_slm",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=1,
    logging_steps=10,
    save_steps=100,
    learning_rate=2e-4,
    fp16=True,
    optim="paged_adamw_8bit"
)

In [10]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds,
    data_collator=DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False
    )
)

## Model Training

In [11]:
trainer.train()

TrainOutput(global_step=1814, training_loss=2.3326187890840338, metrics={'train_runtime': 1530.0634, 'train_samples_per_second': 9.484, 'train_steps_per_second': 1.186, 'total_flos': 2.3083245150142464e+16, 'train_loss': 2.3326187890840338, 'epoch': 1.0})

## Model Saving

In [12]:
model.save_pretrained("finance_slm_model")
tokenizer.save_pretrained("finance_slm_model")

('finance_slm_model/tokenizer_config.json',
 'finance_slm_model/chat_template.jinja',
 'finance_slm_model/tokenizer.json')

## Model Infrence

In [13]:
prompt = "### Question:\nWhat is a mutual fund?\n\n### Answer:\n"

inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

outputs = model.generate(
    **inputs,
    max_new_tokens=100
)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

### Question:
What is a mutual fund?

### Answer:
A mutual fund is a type of investment vehicle that pools money from many investors to invest in a diversified portfolio of stocks, bonds, or other securities.  The investors in the fund are called "shareholders".  The fund is managed by a professional investment manager, who is paid a fee for managing the fund.  The fund is not a separate legal entity, but rather a collection of shares in a single fund.  The

In [28]:
questions = [
    "What is inflation?",
    "What is a mutual fund?",
    "What is a stock market crash?"
]

for q in questions:
    prompt = f"### Question:\n{q}\n\n### Answer:\n"

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=100,
        temperature=0.7
    )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)

    print(f"\n_____________")
    print(response)

_____________
### Question:
What is inflation?

### Answer:
Inflation is the increase in the price of goods and services.  It is a measure of the rate at which the price of goods and services is increasing.  It is not a measure of the amount of money being spent.  It is a measure of the amount of money being earned.  It is a measure of the amount of money being spent.  It is a measure of the amount of money being earned.  It is a measure of the amount of money being spent.  It

_____________
### Question:
What is a mutual fund?

### Answer:
A mutual fund is a type of investment vehicle that pools money from many investors to invest in a diversified portfolio of stocks, bonds, or other securities.  The investors in the fund are called "shareholders".  The fund is managed by a professional investment manager, who is paid a fee for managing the fund.  The fund is not a separate legal entity, but rather a collection of shares in a single fund.  The

_____________
### Question:
What is a stock market crash?

### Answer:
A stock market crash is a sudden and dramatic decline in the price of a stock.  It is not a normal occurrence, and it is not something that happens every day.  It is a very rare event, and it is not something that is likely to happen in the near future.  It is not something that is likely to happen in the near future.  It is not something that is likely to happen in the near future.  It is not something that is likely to happen

In [16]:
dataset = load_dataset("LLukas22/fiqa")

split_dataset = dataset["train"].train_test_split(test_size=0.1, seed=42)

train_ds = split_dataset["train"]
test_ds = split_dataset["test"]

In [17]:
predictions = []
references = []

for sample in test_ds.select(range(20)):

    question = sample["question"]
    true_answer = sample["answer"]

    prompt = f"""### Question:
{question}

### Answer:
"""

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=80,
        temperature=0.7,
        top_p=0.9,
        repetition_penalty=1.2,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id
    )

    generated = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    generated_answer = generated.split("### Answer:")[-1].strip()

    predictions.append(generated_answer)
    references.append(true_answer)

    print("\n ---")
    print("QUESTION:", question)
    print("\nGENERATED:\n", generated_answer)
    print("\nREFERENCE:\n", true_answer)

========================
QUESTION: Is it wise to have plenty of current accounts in different banks?

GENERATED:
 I agree with the other answers that you should not open multiple credit cards.  However, I would suggest opening one credit card per bank account (or at least for your primary account). This is because having a few different types of credit card in each account will be more convenient for making purchases and redeeming points/cashbacks if needed. For example, let's say

REFERENCE:
 You should not open bank accounts just to get additional credit cards. You should be careful about carrying too many credit cards and incurring too much debt as you could find yourself in a situation whereby you may not be able to pay off your monthly interest, much less the principal balance. Credit cards are not insurance. With many years of experience under my belt I can tell you that the best approach is to live within (or below) your means and avoid carrying a balance on credit cards. I carry only one credit card (really a charge card) and I pay off the balance every month. Treat a credit card as a 30 day interest free loan and pay your balance off in full every month...as you progress through life you will save yourself a lot of heartache (and money) if you take this approach.

========================
QUESTION: Transferred Stocks in 1993, sold 2017 taxes

GENERATED:
 It is not uncommon for people to sell stocks when they are younger and the market value of their portfolio has risen. This is called a "re-evaluation" of your investment strategy. If you did this after retirement (over 50 years old) then it would be considered a sale, but before that age the stocks will probably have appreciated more than you

REFERENCE:
 Assuming the stock was worth more at the time she gave it to you than when she bought it, the cost basis would be the amount that she bought it for. You would then pay tax on the increase in value from that time.  Generally it's better to inherit assets than receive them as gifts, since the cost basis of inherited assets is raised to the value at the time of the death of the one leaving the inheritance. You will probably need to find some record of the original amount paid so you can determine the right cost basis.

========================
QUESTION: Currently sole owner of a property. My girlfriend is looking to move in with me and is offering to pay 'rent'. Am I at risk here?

GENERATED:
 This seems like an overreaction.  You are not the landlord, you're just sharing the ownership. So if she moves out without your permission or it becomes clear that you don't want her living there anymore, then you can do whatever you want (whatever includes evicting her). This doesn't mean that she isn't welcome in the house any more

REFERENCE:
 The rent payment is in principle taxable. However, you should be able to take advantage of the "rent a room" scheme, and the proposed rent falls well under the £7,500/year tax threshold for that. So no tax will be actually payable and you don't have to formally declare it as long as you stay below that threshold. You should also be fairly well legally protected in case you do split up in future and you want to remove her. As you would be living there too, she would just be a lodger, not a tenant (technically, an "excluded occupier"). If you did want her to leave you would only need to give reasonable notice and wouldn't need a formal court order if you needed to force her to go. As JBentley points out, there have been court cases where domestic partners contributing to household expenses while the other partner paid the mortgage have later been able to claim that this implied joint ownership. This was on the basis of a "constructive trust" being implicitly setup by the way they arranged their finances. In your case, if there's a clear intention, formalised in writing, for the money to be treated as rent rather than a contribution towards purchasing the property, I think it should make it very hard to claim the contrary later. I would also suggest you be clear about whether the rent includes a share of the utility bills, and that things like groceries would be handled separately and split 50:50 or whatever. As pointed out in a comment, there are template agreements for lodgers you could use a starting point (e.g. this one), but it's likely you'd need to customise it to your circumstances. Another point made in another answer is that there's potential upcoming legislation to give some rights to cohabiting partners. In the current draft, those would kick in after three years or having children. If the bill does come into effect, you'd also be able to sign an opt out, but only after getting legal advice, and it would still be possible (though presumably hard) to persuade a court to overturn an opt out. Overall that does create a small risk to you, but not one that comes directly from your girlfriend paying rent. It's likely that if you are both on an equal financial footing and had always kept your finances separate, that there wouldn't be any award made anyway. And you can't run your entire life on hypothetical risks.

========================
QUESTION: What size "nest egg" should my husband and I have, and by what age?

GENERATED:
 We've been married for 10 years now. We had a small nest egg in our late twenties but we didn't feel like saving enough money to build a big house or anything fancy. So at that point we felt pretty good about having no debts and being able to live comfortably without worrying about the future. Our current savings is around $50K

REFERENCE:
 There's a bit of working backwards that's required.   This is a summary of a spreadsheet I wrote which helps to get to the answer. What you see here is that at age 25, one might have saved about a half year's salary, assuming they worked 5 years. The numbers grow exponentially to at 65, about 15 years salary saved. This will allow a withdrawal of about 60% final income each year using the 4% guideline. More will come from Social Security in the States to get closer to 100%. The sheet start with assumptions, a 10% per year rate of saving, and an 8% annual return. Salary is assumed to rise 3% per year. One can choose their age, enter their current numbers and their own assumptions. I had to include some numbers and at the time, 8% seemed reasonable. Not so sure today. What I do like is the concept of viewing savings in terms of 'years salary' as this leads to replacement rate. Will $1M be enough for you? Only you can answer that. But the goal of 80-100% replacement income is reasonable and this sheet can be used to understand the goals along the way. (note, the uploaded sheet had 15% saving rate, not the 10 I thought. I used 15 to show a 10% saving along with a 5% match to one's 401(k). Those interested are welcome to enter their own numbers. The one objection I've seen is the increase to salary. Increases tend to be higher in the first 20 than the second, or so I'm told.)

========================
QUESTION: What is the difference between fund and portfolio?

GENERATED:
 The two are not related, except that a fund represents an investment in stocks or other assets.  A portfolio represents all of your financial holdings together (including bonds). So if you have $100k invested in mutual funds but also own several hundred dollars' worth of bonds, it would be best to view both as part of your overall investment strategy

REFERENCE:
 A fund is a portfolio, in that it is a collection, so the term is interchangeable for the most part.  Funds are made up of a combination of equities positions (i.e., stocks, bonds, etc.) plus some amount of un-invested cash. Most of the time, when people are talking about a "fund", they are describing what is really an investment strategy.  In other words, an example would be a "Far East Agressive" fund (just a made up name for illustration here), which focuses on investment opportunities in the Far East that have a higher level of risk than most other investments, thus they provide better returns for the investors.  The "portfolio" part of that is what the stocks are that the fund has purchased and is holding on behalf of its investors.  Other funds focus on municipal bonds or government bonds, and the list goes on. I hope this helps. Good luck!

========================
QUESTION: U.S. Mutual Fund Supermarkets: Where are some good places to buy mutual funds?

GENERATED:
 I'm curious about the "Betterment" fund mentioned in the comments above. I have a friend who uses it, and I think that it seems like a great idea. The reason why I am interested is because they seem to offer an excellent investing experience with no fees (for now).   http://www.betterment.com/ They also appear to be offering low

REFERENCE:
 There are hundreds of entities which offer mutual funds - too many to adequately address here. If you need to pick one, just go with Vanguard for the low low low fees. Yes, this is important. A typical expense ratio of 1% may not sound like much until you realize that the annualized real rate of return on the stock market - after inflation - is about 4%... so the fund eats a quarter of your earnings. (Vanguard's typical expense ratios are closer to 0.1-0.2%). If your company offers a tax-deferred retirement account such as a 401(k), you'll probably find it advantageous to use whatever funds that plan offers just to get the tax advantage, and roll over the account to a cheaper provider when you change employers. You can also buy mutual funds and exchange-traded funds (ETFs) through most brokerages. E*Trade has a nice mutual fund screener, with over 6700 mutual funds and 1180 ETFs. Charles Schwab has one you can browse without even having an account.

========================
QUESTION: Car financed at 24.90% — what can I do?

GENERATED:
 You could try to get the dealer (or your bank) to increase that rate by a percentage point, but it seems unlikely they would do this without asking for an exception from their credit card agreement with you (which may or may not be allowed). You should ask them why they are charging such high interest rates and how they justify those rates. If it's because of a special finan

REFERENCE:
 Anytime you borrow money at that rate, you are getting ripped off.   One way to rectify this situation is to pay the car off as soon as possible.  You can probably get a second job that makes $1000 per month.  If so you will be done in 4 months.    Do that and you will pay less than $300 in interest.  It is a small price to pay for an important lesson. While you can save some money refinancing, working and paying the loan off is, in my opinion a better option.  Even if you can get the rate down to 12%, you are still giving too much money to banks.

========================
QUESTION: What is the incentive for a bank to refinance a mortgage at a lower rate?

GENERATED:
 The banks would be willing to take on the risk of higher interest rates, but they'd have to sell off some assets.  The lender has an obligation to pay back the loan if it defaults and therefore cannot charge you more than what they originally promised (plus any additional fees). If your interest rate goes up by 2%, then you won't get paid as much from

REFERENCE:
 It also reduces risk from the bank's eyes. Believe it or not, they do lose out when people don't pay on their mortgages. Take the big 3 (Wells, Chase and BoA). If they have 50 million mortgages between the 3 of them and 20% of people at one point won't be able to pay their mortgage due to loss of income or other factors, this presents a risk factor. Although interest payments are still good, reducing their principal and interest keeps them tied down for additional (or sometimes shorter) time, but now they are more likely to keep getting those payments. That's why credit cards back in 07 and 08 reduced limits for customers. The risk factor is huge now for these financial institutions. Do your research, sometimes a refi isn't the best option. Sometimes it is.

========================
QUESTION: What emergencies could justify a highly liquid emergency fund?

GENERATED:
 I'm not sure I understand your question. Are you asking if having a very high liquidity (which may or may not be an asset) is the right answer to every problem? The answer is no, there are many problems that don't require this kind of liquidity.  If you were in a car accident and needed cash for medical expenses, you would need money fast

REFERENCE:
 I tend to agree that the need for liquidity is overplayed in this day and age.  We live in a world of electronic transfers that take only a couple days at most.  With my brokerage account I can go from stock to gas in my tank via debit card in about 3 days. We're a long way away from the days when it took weeks, phone calls, and physical checks in the mail to go from stock to cash in your hand.  We've also moved a long way away from limited credit/debit card acceptance.  It was not long ago that my mechanic didn't accept credit cards.  Locksmiths didn't carry a square reader on their iPhone 10 years ago.   However, don't expect debt to always be available.  Many many many people with strong income and stellar credit histories had their credit/HELOC limits slashed from 2008-2010 while banks pared back risk.  A cash position of a size that makes sense gives you a high level of short term control; you aren't reliant on someone else's money. Liquidity isn't the main issue with emergency funds.  The main issue is psychological.  Build a foundation rather than overly optimistically chasing yield.

========================
QUESTION: Moving savings to Canada?

GENERATED:
 If you are going through a bank or building society, and if the bank is licensed in the UK (and/or has branches there), then it should be able to handle your money.  If they're not licenced, then I would avoid them completely. Some banks don't like foreigners doing business with their countries because of lax regulation on currency fluctuations

REFERENCE:
 It is absolutely feasible to move your savings into Canada. There are a few ways you can do it. However it is unlikely you will benefit or avoid risk by doing so. You could directly hold your savings in the CAD. Investing in Canadian bonds achieves a similar goal as holding your money in the CAD. By doing so you will be getting re-payed with CAD. Some Canadian companies also trade on US markets. In addition some brokerage firms allow you to trade on Canadian markets. The problem with any of the options is the assumption that Canadian banks will fare better then US banks. The entire globe is very dependent on each other, especially the more developed nations. If large US banks were to fail it would create a domino effect which would spiral into a global credit crunch. It wouldn't matter if your invested in Canadian companies or US companies they would all suffer as would the global economy. So it would probably be more valid to refer to your question - enter link description here If you are referring to weather the Canadian bonds would be a safer investment over US Treasuries it would all depend on the scenario at hand. Investors would probably flock to both treasuries.

========================
QUESTION: Are solar cell panels and wind mills worth the money?

GENERATED:
 Wind turbines do not produce energy, they harness it. Solar cells can be installed on a roof, or in the ground (as shown at http://www.youtube.com/watch?v=MZ3K2g5Ln7Q). They can also be used to charge batteries, but that's another story entirely. The amount of energy generated

REFERENCE:
 Solar water heaters are definitely worth the money (if you live in sunny states like South-South-West or Hawaii, at least). In some countries (like Greece, Cyprus and Israel, to name a few) most people use hot water from the solar heaters almost exclusively. I pay $30-$40 a month to PG&E for the privilege. Unfortunately, in the US these heaters are much more expensive than they are in the more advanced European countries, so all the savings go to drain because of the vast price difference ($300 for a gas heater vs $2000 for a solar heater).

========================
QUESTION: What is the valuation of a company based on?

GENERATED:
 I don't think this question has anything to do with stock prices.  A person who thinks that this question should be asked (or is asking it) will likely have some idea about how he/she arrived at their answer, but I suspect that your initial assumption is wrong; they are trying to figure out something else entirely and you are just making noise for no reason.  This is not

REFERENCE:
 There is no such thing as a correct value. There are different ways to calculate (read: guess) an anticipated value, but neither of them is the "correct" one. Last not least this depends on your interpretation of the term "correct" in that context.  Why do you think paid Facebook such a huge amount for WhatsApp? Surely not, because it was the "correct" value.

========================
QUESTION: Can I prove having savings without giving out the account number?

GENERATED:
 A person who is looking for money can't prove that they have it.  They just want to be able to say "I don't know where this $10,000 went". The only way you will get a response from them is if there are some physical signs of your possession - like leaving behind an envelope with a receipt and no cash inside or something

REFERENCE:
 Ask your bank to write a letter asserting that you have $xxxxx on deposit with them, on their letterhead? Though realistically, the chance of your getting hit with identity theft In this situation, when you presumably know exactly who you're dealing with, are vanishingly small.

========================
QUESTION: Self-directed RRSP into mortgage investment

GENERATED:
 This is a great question.  I think it's worth considering whether you are using the RRSP to purchase an asset or just as part of your overall portfolio. If you want to buy something with the money in the RRSP, then you should consider other options. This might include a taxable account and some sort of mutual fund for example. The reason this doesn'

REFERENCE:
 The Globe and Mail has an interesting article on what you can do with your RRSPs. Be aware that the article is from early 2011 and rules change. They describe holding your own mortgage inside your RRSP. That is, if you have $100,000 inside your RRSP already and your remaining mortgage is $100,000, you can use that money to pay off your mortgage, then pay back the money at interest, generating a tax-deferred profit inside your RRSP. That approach may be viable, though you'd want to talk to your accountant first. I'd be very cautious about loaning money to someone else for a second mortgage using my RRSP, though. Second mortgages are inherently risky, so this is a very speculative investment. Once you make an RRSP contribution, that space is used up (barring a couple of exceptions such as the life-long learning plan). So, let's say you used $100,000 of your RRSP to loan to someone for a second mortgage. Any interest payments should be sheltered inside the RRSP (substantial benefit), but if the person defaults on the second mortgage (which you should expect to be a significant possibility), you've lost your entire $100,000 contribution room (as well as, obviously, the $100,000 that you loaned out). I can't tell you whether or not it makes sense to invest in risky second-mortgage loans and I can't tell you whether, if you choose to do so, it definitely should be done inside an RRSP. There are substantial risks in the loan and there are both costs and benefits to doing so inside an RRSP. Hopefully, though, I've helped you understand the questions you should be asking yourself.

========================
QUESTION: Question about stock taxes buy/sell short term

GENERATED:

In [23]:
rouge = evaluate.load("rouge")

results = rouge.compute(
    predictions=predictions,
    references=references
)

print(results)

{'rouge1': np.float64(0.20784340968464013), 'rouge2': np.float64(0.022801555252304546), 'rougeL': np.float64(0.10404363608639566), 'rougeLsum': np.float64(0.10385842341427853)}

In [27]:
bertscore = evaluate.load("bertscore")

results = bertscore.compute(
    predictions=predictions,
    references=references,
    lang="en"
)

avg_f1 = sum(results["f1"]) / len(results["f1"])

print("Average BERTScore F1:", avg_f1)

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: roberta-large
Key                             | Status     |
--------------------------------+------------+-
lm_head.layer_norm.bias         | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
pooler.dense.bias               | MISSING    |
pooler.dense.weight             | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Average BERTScore F1: 0.8265547603368759